//import { StringifyOptions } from 'querystring';
import { NodeCompatibleEventEmitter } from 'rxjs/internal/observable/fromEvent';
import { TextDataModel } from './TextData.model';

export class TextContentsModel {
  dataok: boolean;
  bannerbottom: string;
  opinions_title: string;
  opinions_view: string;
  recommended_message1: string;
  recommended_message2: string;
  recommended_button: string;
  form_title: string;
  form_name: string;
  form_email: string;
  form_message: string;
  form_policy: string;
  form_link: string;
  form_button: string;
  bannertop_tittle: string;
  bannertop_message1: string;
  bannertop_message2: string;
  bannertop_input: string;
  bannertop_button: string;
  bannertop_icons_guide: string;
  bannertop_icons_group: string;
  bannertop_icons_talk: string;
  bannertop_icons_price: string;
  footer_menu1_title: string;
  footer_menu1_who: string;
  footer_menu1_blog: string;
  footer_menu1_help: string;
  footer_menu1_covid: string;
  footer_menu1_contact: string;
  footer_menu2_title: string;
  footer_menu2_policy: string;
  footer_menu2_notice: string;
  footer_menu2_cookie: string;
  footer_menu2_purchase: string;
  menu_who: string;
  menu_blog: string;
  menu_help: string;
  menu_contact: string;
  menu_hello: string;
  menu_recovery: string;
  menu_register: string;
  menu_count: string;
  menu_login: string;
  menu_cart: string;
  cart_search: string;
  cart_actividades: string;
  cart_finalizar: string;
  cart_vacio: string;
  cart_pagoseguro: string;
  cart_graciascompra: string;
  cart_modificarcarrito: string;
  cart_registrate: string;
  cart_ohazlogin: string;
  cart_registrar: string;
  cart_datosreserva: string;
  cart_formregistro_name: string;
  cart_formregistro_surname: string;
  cart_formregistro_email: string;
  cart_formregistro_password: string;
  cart_formregistro_prefijo: string;
  cart_formregistro_calle: string;
  cart_formregistro_numero: string;
  cart_formregistro_localidad: string;
  cart_formregistro_estado: string;
  cart_formregistro_pais: string;
  cart_modalcuenta_title: string;
  cart_modalcuenta_iniciarsesion: string;
  cart_modalcuenta_usuarioemail: string;
  cart_modalcuenta_password: string;
  cart_modalcuenta_recordarme: string;
  cart_modalcuenta_oaccede: string;
  cart_modalcuenta_fb: string;
  cart_modalcuenta_go: string;
  cart_procesopago: string;
  cart_cabecera_revisapedido: string;
  cart_cabecera_datospersonales: string;
  cart_cabecera_metodospago: string;
  bannertop_verresultados: string;
  buscador_title: string;
  buscador_buscarpo: string;
  buscador_tipodeplan: string;
  buscador_resultado: string;
  buscador_ordenar: string;
  buscador_verdisponibilidad: string;
  buscador_idiomas: string;
  buscador_precio: string;
  buscador_franja: string;
  buscador_duracion: string;
  buscador_caracteristicas: string;
  buscador_quitarfiltros: string;
  buscador_veractividades: string;
  buscador_hoy: string;
  buscador_manana: string;
  buscador_borrar: string;
  buscador_aplicar: string;
  buscador_enero: string;
  buscador_febrero: string;
  buscador_marzo: string;
  buscador_abril: string;
  buscador_mayo: string;
  buscador_junio: string;
  buscador_julio: string;
  buscador_agosto: string;
  buscador_septiembre: string;
  buscador_octubre: string;
  buscador_noviembre: string;
  buscador_diciembre: string;
  buscador_actividadesencontradas: string;
  buscador_ordenadopor: string;
  buscador_relevancia: string;
  buscador_preciomasbajo: string;
  buscador_preciomasalto: string;
  buscador_duracionmayor: string;
  buscador_duracionmenor: string;
  buscador_porpersona: string;
  login_micuenta: string;
  login_reservas: string;
  login_ayuda: string;
  login_cerrarsesion: string;
  login_accedeatucuenta: string;
  login_usuario: string;
  login_password: string;
  login_recordarme: string;
  login_iniciarsesion: string;
  login_heolvidado: string;
  login_olvidemipassword: string;
  login_enviarcodigo: string;
  login_enviar: string;
  login_notienescuenta: string;
  login_registrarseaqui: string;
  login_Registro: string;
  login_registro_email: string;
  login_registro_password: string;
  login_registro_name: string;
  login_registro_surname: string;
  login_registro_prefijo: string;
  login_registro_phone: string;
  login_registro_address: string;
  login_registro_number: string;
  login_registro_country: string;
  login_registro_state: string;
  login_registro_city: string;
  login_registro_registrar: string;
  login_registro_sitengo: string;
  login_registro_iralogin: string;
  menu_cart_finalizarreserva: string;
  buscador_diacompleto: string;
  buscador_horas: string;
  buscador_disponible: string;
  buscador_adulto: string;
  buscador_vendidas: string;
  buscador_maximaspersonas: string;
  buscador_reservar: string;
  buscador_total: string;
  buscador_fecha: string;
  buscador_hora: string;
  buscador_idioma: string;
  buscador_personas: string;
  buscador_desde: string;
  buscador_compartir: string;
  buscador_tambientepuede: string;
  buscador_actividades: string;
  ayudas_title: string;
  ayudas_text1: string;
  ayudas_question1: string;
  ayudas_answer1: string;
  ayudas_question2: string;
  ayudas_answer2: string;
  ayudas_question3: string;
  ayudas_answer3: string;
  ayudas_question4: string;
  ayudas_answer4: string;
  ayudas_question5: string;
  ayudas_answer5: string;
  ayudas_noencuentras: string;
  ayudas_escribenosunwhatsapp: string;
  ayudas_llamanosal: string;
  ayudas_escribenosa: string;
  ayudas_oatravesde: string;
  quienes_title: string;
  quienes_text1: string;
  quienes_title2a: string;
  quienes_title2b: string;
  quienes_text2: string;
  quienes_text3: string;
  quienes_text4: string;
  quienes_text5: string;
  micuenta_hola: string;
  micuenta_title: string;
  micuenta_menu_micuenta: string;
  micuenta_menu_reservas: string;
  micuenta_ayuda: string;
  micuenta_form_datospersonales: string;
  micuenta_form_name: string;
  micuenta_form_surname: string;
  micuenta_form_email: string;
  micuenta_form_prefijo: string;
  micuenta_form_telefono: string;
  micuenta_form_tipodoc: string;
  micuenta_form_numerotipodoc: string;
  micuenta_form_user: string;
  micuenta_form_company: string;
  micuenta_form_guardarcambios: string;
  micuenta_form_datosfacturacion: string;
  micuenta_form_address: string;
  micuenta_form_number: string;
  micuenta_form_country: string;
  micuenta_form_cp: string;
  micuenta_form_state: string;
  micuenta_form_city: string;
  micuenta_reservas_title: string;
  buscador_detail_description: string;
  buscador_detail_price: string;
  buscador_detail_adultos: string;
  buscador_detail_infantil: string;
  buscador_detail_duracion: string;
  buscador_detail_idiomas: string;
  buscador_detail_cuandoreservar: string;
  buscador_detail_accesibilidad: string;
  buscador_detail_pets: string;
  buscador_detail_cancelation: string;
  buscador_detail_puntoencuetro: string;
  buscador_detail_nosencontramos: string;
  buscador_detail_verengooglemaps: string;
  buscador_detail_verdescripcion: string;
  buscador_lunes: string;
  buscador_martes: string;
  buscador_miercoles: string;
  buscador_jueves: string;
  buscador_viernes: string;
  buscador_sabado: string;
  buscador_domingo: string;
  buscador_1: string;
  buscador_2: string;
  buscador_3: string;
  buscador_filtrar: string;
  buscador_visitatemporada: string;
  buscador_sinresultados: string;
  buscador_sugerencias: string;

  politicascookies_title: string;
  politicascookies_text: string;
  politicasprivacidad_title: string;
  politicasprivacidad_text: string;
  politicascompra_title: string;
  politicascompra_text: string;
  avisolegal_title: string;
  avisolegal_text: string;


  cookies_title: string;
  cookies_utilizamos: string;
  cookies_aceptar: string;
  cookies_denegar: string;
  cookies_configurar: string;
  cookies_verinfo: string;
  cookies_preferencias: string;
  cookies_seguridad: string;
  cookies_cookiesson: string;
  cookies_desdepanel: string;
  cookies_esenciales: string;
  cookies_sonaquellas: string;
  cookies_noseria: string;
  cookies_funcionalidad: string;
  cookies_registranlainfo: string;
  cookies_permitendar: string;
  cookies_rendimiento: string;
  cookies_ayudananalizar: string;
  cookies_midentrafico: string;
  cookies_seguimiento: string;
  cookies_publicidadsegmentada: string;
  cookies_mostraranuncios: string;
  cookies_tab_seguridad: string;
  cookies_tab_necesarias: string;
  cookies_tab_funcionalidad: string;
  cookies_tab_rendimiento: string;
  cookies_tab_seguimiento: string;
  cookies_guardar: string;
  modificar: string;
  carrito: string;
  continuar: string;
  paso1: string;
  paso2: string;
  paso3: string;
  acompanantes: string;
  edad: string;
  privada: string;
  confirmada: string;
  pendiente: string;
  reserva: string;
  touren: string;
  relacionadas: string;
  selecciona_hora: string;
  selecciona_idioma: string;
  selecciona_personas: string;
  implica: string;
  contratarprivada: string;
  si: string;
  no: string;
  detalle: string;
  reservar_mas: string;
  logincon: string;
  hemos_enviado: string;
  detalle_pedido: string;

  constructor() {
    this.dataok  = false;
    this.bannerbottom = '';
    this.opinions_title = '';
    this.opinions_view = '';
    this.recommended_message1 = '';
    this.recommended_message2 = '';
    this.recommended_button = '';
    this.form_title = '';
    this.form_name = '';
    this.form_email = '';
    this.form_message = '';
    this.form_policy = '';
    this.form_link = '';
    this.form_button = '';
    this.bannertop_tittle = '';
    this.bannertop_message1 = '';
    this.bannertop_message2 = '';
    this.bannertop_input = '';
    this.bannertop_button = '';
    this.bannertop_icons_guide = '';
    this.bannertop_icons_group = '';
    this.bannertop_icons_talk = '';
    this.bannertop_icons_price = '';
    this.footer_menu1_title = '';
    this.footer_menu1_who = '';
    this.footer_menu1_blog = '';
    this.footer_menu1_help = '';
    this.footer_menu1_covid = '';
    this.footer_menu1_contact = '';
    this.footer_menu2_title = '';
    this.footer_menu2_policy = '';
    this.footer_menu2_notice = '';
    this.footer_menu2_cookie = '';
    this.footer_menu2_purchase = '';
    this.menu_who = '';
    this.menu_blog = '';
    this.menu_help = '';
    this.menu_contact = '';
    this.menu_hello = '';
    this.menu_recovery = '';
    this.menu_register = '';
    this.menu_count = '';
    this.menu_login = '';
    this.menu_cart = '';
    this.cart_search = '';
    this.cart_actividades = '';
    this.cart_finalizar = '';
    this.cart_vacio = '';
    this.cart_pagoseguro = '';
    this.cart_graciascompra = '';
    this.cart_modificarcarrito = '';
    this.cart_registrate = '';
    this.cart_ohazlogin = '';
    this.cart_registrar = '';
    this.cart_datosreserva = '';
    this.cart_formregistro_name = '';
    this.cart_formregistro_surname = '';
    this.cart_formregistro_email = '';
    this.cart_formregistro_password = '';
    this.cart_formregistro_prefijo = '';
    this.cart_formregistro_calle = '';
    this.cart_formregistro_numero = '';
    this.cart_formregistro_localidad = '';
    this.cart_formregistro_estado = '';
    this.cart_formregistro_pais = '';
    this.cart_modalcuenta_title = '';
    this.cart_modalcuenta_iniciarsesion = '';
    this.cart_modalcuenta_usuarioemail = '';
    this.cart_modalcuenta_password = '';
    this.cart_modalcuenta_recordarme = '';
    this.cart_modalcuenta_oaccede = '';
    this.cart_modalcuenta_fb = '';
    this.cart_modalcuenta_go = '';
    this.cart_procesopago = '';
    this.cart_cabecera_revisapedido = '';
    this.cart_cabecera_datospersonales = '';
    this.cart_cabecera_metodospago = '';
    this.bannertop_verresultados = '';
    this.buscador_title = '';
    this.buscador_buscarpo = '';
    this.buscador_tipodeplan = '';
    this.buscador_resultado = '';
    this.buscador_ordenar = '';
    this.buscador_verdisponibilidad = '';
    this.buscador_idiomas = '';
    this.buscador_precio = '';
    this.buscador_franja = '';
    this.buscador_duracion = '';
    this.buscador_caracteristicas = '';
    this.buscador_quitarfiltros = '';
    this.buscador_veractividades = '';
    this.buscador_visitatemporada = '';
    this.buscador_hoy = '';
    this.buscador_manana = '';
    this.buscador_borrar = '';
    this.buscador_aplicar = '';
    this.buscador_enero = '';
    this.buscador_febrero = '';
    this.buscador_marzo = '';
    this.buscador_abril = '';
    this.buscador_mayo = '';
    this.buscador_junio = '';
    this.buscador_julio = '';
    this.buscador_agosto = '';
    this.buscador_septiembre = '';
    this.buscador_octubre = '';
    this.buscador_noviembre = '';
    this.buscador_diciembre = '';
    this.buscador_actividadesencontradas = '';
    this.buscador_ordenadopor = '';
    this.buscador_relevancia = '';
    this.buscador_preciomasbajo = '';
    this.buscador_preciomasalto = '';
    this.buscador_duracionmayor = '';
    this.buscador_duracionmenor = '';
    this.buscador_porpersona = '';
    this.buscador_sugerencias = '';
    this.login_micuenta = '';
    this.login_reservas = '';
    this.login_ayuda = '';
    this.login_cerrarsesion = '';
    this.login_accedeatucuenta = '';
    this.login_usuario = '';
    this.login_password = '';
    this.login_recordarme = '';
    this.login_iniciarsesion = '';
    this.login_heolvidado = '';
    this.login_olvidemipassword = '';
    this.login_enviarcodigo = '';
    this.login_enviar = '';
    this.login_notienescuenta = '';
    this.login_registrarseaqui = '';
    this.login_Registro = '';
    this.login_registro_email = '';
    this.login_registro_password = '';
    this.login_registro_name = '';
    this.login_registro_surname = '';
    this.login_registro_prefijo = '';
    this.login_registro_phone = '';
    this.login_registro_address = '';
    this.login_registro_number = '';
    this.login_registro_country = '';
    this.login_registro_state = '';
    this.login_registro_city = '';
    this.login_registro_registrar = '';
    this.login_registro_sitengo = '';
    this.login_registro_iralogin = '';
    this.menu_cart_finalizarreserva = '';
    this.buscador_diacompleto = '';
    this.buscador_horas = '';
    this.buscador_disponible = '';
    this.buscador_adulto = '';
    this.buscador_vendidas = '';
    this.buscador_maximaspersonas = '';
    this.buscador_reservar = '';
    this.buscador_total = '';
    this.buscador_fecha = '';
    this.buscador_hora = '';
    this.buscador_idioma = '';
    this.buscador_personas = '';
    this.buscador_desde = '';
    this.buscador_compartir = '';
    this.buscador_tambientepuede = '';
    this.buscador_actividades = '';
    this.buscador_sinresultados = '';
    this.ayudas_title = '';
    this.ayudas_text1 = '';
    this.ayudas_question1 = '';
    this.ayudas_answer1 = '';
    this.ayudas_question2 = '';
    this.ayudas_answer2 = '';
    this.ayudas_question3 = '';
    this.ayudas_answer3 = '';
    this.ayudas_question4 = '';
    this.ayudas_answer4 = '';
    this.ayudas_question5 = '';
    this.ayudas_answer5 = '';
    this.ayudas_noencuentras = '';
    this.ayudas_escribenosunwhatsapp = '';
    this.ayudas_llamanosal = '';
    this.ayudas_escribenosa = '';
    this.ayudas_oatravesde = '';
    this.quienes_title = '';
    this.quienes_text1 = '';
    this.quienes_title2a = '';
    this.quienes_title2b = '';
    this.quienes_text2 = '';
    this.quienes_text3 = '';
    this.quienes_text4 = '';
    this.quienes_text5 = '';
    this.micuenta_hola = '';
    this.micuenta_title = '';
    this.micuenta_menu_micuenta = '';
    this.micuenta_menu_reservas = '';
    this.micuenta_ayuda = '';
    this.micuenta_form_datospersonales = '';
    this.micuenta_form_name = '';
    this.micuenta_form_surname = '';
    this.micuenta_form_email = '';
    this.micuenta_form_prefijo = '';
    this.micuenta_form_telefono = '';
    this.micuenta_form_tipodoc = '';
    this.micuenta_form_numerotipodoc = '';
    this.micuenta_form_user = '';
    this.micuenta_form_company = '';
    this.micuenta_form_guardarcambios = '';
    this.micuenta_form_datosfacturacion = '';
    this.micuenta_form_address = '';
    this.micuenta_form_number = '';
    this.micuenta_form_country = '';
    this.micuenta_form_cp = '';
    this.micuenta_form_state = '';
    this.micuenta_form_city = '';
    this.micuenta_reservas_title = '';
    this.buscador_detail_description = '';
    this.buscador_detail_price = '';
    this.buscador_detail_adultos = '';
    this.buscador_detail_infantil = '';
    this.buscador_detail_duracion = '';
    this.buscador_detail_idiomas = '';
    this.buscador_detail_cuandoreservar = '';
    this.buscador_detail_accesibilidad = '';
    this.buscador_detail_pets = '';
    this.buscador_detail_cancelation = '';
    this.buscador_detail_puntoencuetro = '';
    this.buscador_detail_nosencontramos = '';
    this.buscador_detail_verengooglemaps = '';
    this.buscador_detail_verdescripcion = '';
    this.buscador_lunes = '';
    this.buscador_martes = '';
    this.buscador_miercoles = '';
    this.buscador_jueves = '';
    this.buscador_viernes = '';
    this.buscador_sabado = '';
    this.buscador_domingo = '';
    this.buscador_1 = '';
    this.buscador_2 = '';
    this.buscador_3 = '';
    this.buscador_filtrar = '';

    this.politicascookies_title = '';
    this.politicasprivacidad_title = '';
    this.politicasprivacidad_text = '';
    this.politicascompra_title = '';
    this.politicascompra_text = '';
    this.avisolegal_title = '';
    this.avisolegal_text = '';

    this.cookies_title = '';
    this.cookies_utilizamos = '';
    this.cookies_aceptar = '';
    this.cookies_denegar = '';
    this.cookies_configurar = '';
    this.cookies_verinfo = '';
    this.cookies_preferencias = '';
    this.cookies_seguridad = '';
    this.cookies_cookiesson = '';
    this.cookies_desdepanel = '';
    this.cookies_esenciales = '';
    this.cookies_sonaquellas = '';
    this.cookies_noseria = '';
    this.cookies_funcionalidad = '';
    this.cookies_registranlainfo = '';
    this.cookies_permitendar = '';
    this.cookies_rendimiento = '';
    this.cookies_ayudananalizar = '';
    this.cookies_midentrafico = '';
    this.cookies_seguimiento = '';
    this.cookies_publicidadsegmentada = '';
    this.cookies_mostraranuncios = '';
    this.cookies_tab_seguridad = '';
    this.cookies_tab_necesarias = '';
    this.cookies_tab_funcionalidad = '';
    this.cookies_tab_rendimiento = '';
    this.cookies_tab_seguimiento = '';
    this.cookies_guardar = '';
    this.modificar = '';
    this.carrito = '';
    this.continuar = '';
    this.paso1 = '';
    this.paso2 = '';
    this.paso3 = '';
    this.acompanantes = '';
    this.edad = '';
    this.privada = '';
    this.confirmada = '';
    this.pendiente = '';
    this.reserva = '';
    this.touren = '';
    this.relacionadas = '';
    this.implica = '';
    this.contratarprivada = '';
    this.si = '';
    this.no = '';
    this.detalle = '';
    this.reservar_mas = '';

    this.selecciona_hora = '';
    this.selecciona_idioma = '';
    this.selecciona_personas = '';
    this.logincon = '';
    this.hemos_enviado = '';
    this.detalle_pedido = '';


  }
}
