// generated by @nguniversal/express-engine
const port = process.env.PORT || 4000;

const server = require('./server');

server.app.listen(port, () => {
console.log(`Listening on: http://localhost:${port}`);
});
