// generated by @nguniversal/express-engine
const port = process.env.PORT || 4000;

const server = require('./dist/madguides/server/main.js');

server.app().listen(port, () => {
console.log(`Listening on: http://localhost:${port}`);//
});
